import type {
  Confidence,
  Observation,
  ScenarioTime,
} from '../../core/contracts';
import { scenario01EntityIds } from './baseline';

export const SCENARIO_01_START_TIME: ScenarioTime = 7 * 60 + 40;

const currentTelemetryConfidence: Confidence = {
  level: 'high',
  reasons: [
    {
      type: 'source',
      effect: 'increase',
      description: 'Current reading received from the registered telemetry source.',
    },
  ],
};

const currentSystemConfidence: Confidence = {
  level: 'high',
  reasons: [
    {
      type: 'source',
      effect: 'increase',
      description: 'Current state received from the registered operational system.',
    },
  ],
};

const recentHumanReportConfidence: Confidence = {
  level: 'high',
  reasons: [
    {
      type: 'source',
      effect: 'increase',
      description: 'Recent report received through an independent operational channel.',
    },
  ],
};

export const scenario01BaselineObservations: Observation[] = [
  {
    id: 'observation.baseline.gpz.supply-state',
    entityId: scenario01EntityIds.gridSubstation,
    metric: 'power.supplyState',
    value: 'normal',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'system', id: 'gpz-operator-channel' },
    quality: 'good',
    confidence: currentSystemConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.gpz.feeder-state',
    entityId: scenario01EntityIds.gridSubstation,
    metric: 'power.feederState',
    value: 'closed',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'system', id: 'gpz-operator-channel' },
    quality: 'good',
    confidence: currentSystemConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.gpz.load-percentage',
    entityId: scenario01EntityIds.gridSubstation,
    metric: 'power.loadPercentage',
    value: 62,
    unit: '%',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'telemetry', id: 'gpz-telemetry' },
    quality: 'good',
    confidence: currentTelemetryConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.suw.output-pressure',
    entityId: scenario01EntityIds.waterStation,
    metric: 'water.outputPressure',
    value: 4.6,
    unit: 'bar',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'telemetry', id: 'suw-telemetry-via-r4' },
    quality: 'good',
    confidence: currentTelemetryConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.suw.reservoir-level',
    entityId: scenario01EntityIds.waterStation,
    metric: 'water.reservoirLevel',
    value: 78,
    unit: '%',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'telemetry', id: 'suw-telemetry-via-r4' },
    quality: 'good',
    confidence: currentTelemetryConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.suw.pump-state',
    entityId: scenario01EntityIds.waterStation,
    metric: 'water.pumpState',
    value: {
      pump1: 'running',
      pump2: 'running',
      pump3: 'standby',
    },
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'telemetry', id: 'suw-telemetry-via-r4' },
    quality: 'good',
    confidence: currentTelemetryConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.r4.power-mode',
    entityId: scenario01EntityIds.communicationsGateway,
    metric: 'communications.powerMode',
    value: 'grid',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'telemetry', id: 'r4-telemetry' },
    quality: 'good',
    confidence: currentTelemetryConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.r4.link-quality',
    entityId: scenario01EntityIds.communicationsGateway,
    metric: 'communications.linkQuality',
    value: 'good',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'telemetry', id: 'r4-telemetry' },
    quality: 'good',
    confidence: currentTelemetryConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.r4.packet-loss',
    entityId: scenario01EntityIds.communicationsGateway,
    metric: 'communications.packetLoss',
    value: 0.2,
    unit: '%',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'telemetry', id: 'r4-telemetry' },
    quality: 'good',
    confidence: currentTelemetryConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.hospital.essential-services',
    entityId: scenario01EntityIds.countyHospital,
    metric: 'health.essentialServicesPosture',
    value: 'maintained',
    observedAt: SCENARIO_01_START_TIME - 5,
    receivedAt: SCENARIO_01_START_TIME,
    source: {
      type: 'human-report',
      id: 'hospital-duty-report',
      organisation: 'County Hospital Nowy Brzeg',
    },
    quality: 'good',
    confidence: recentHumanReportConfidence,
    classification: 'report',
  },
  {
    id: 'observation.baseline.hospital.water-margin',
    entityId: scenario01EntityIds.countyHospital,
    metric: 'health.waterMargin',
    value: 8,
    unit: 'h',
    observedAt: SCENARIO_01_START_TIME - 5,
    receivedAt: SCENARIO_01_START_TIME,
    source: {
      type: 'human-report',
      id: 'hospital-duty-report',
      organisation: 'County Hospital Nowy Brzeg',
    },
    quality: 'good',
    confidence: recentHumanReportConfidence,
    classification: 'report',
  },
  {
    id: 'observation.baseline.ag400.resource-state',
    entityId: scenario01EntityIds.mobileGenerator,
    metric: 'logistics.resourceState',
    value: 'available',
    observedAt: SCENARIO_01_START_TIME,
    receivedAt: SCENARIO_01_START_TIME,
    source: { type: 'system', id: 'wczk-resource-registry' },
    quality: 'good',
    confidence: currentSystemConfidence,
    classification: 'fact',
  },
  {
    id: 'observation.baseline.z17.route-state',
    entityId: scenario01EntityIds.accessRoute,
    metric: 'logistics.routeState',
    value: 'open',
    observedAt: SCENARIO_01_START_TIME - 2,
    receivedAt: SCENARIO_01_START_TIME,
    source: {
      type: 'external',
      id: 'road-authority-feed',
      organisation: 'Nowy Brzeg Road Authority',
    },
    quality: 'good',
    confidence: recentHumanReportConfidence,
    classification: 'report',
  },
  {
    id: 'observation.baseline.z17.travel-time',
    entityId: scenario01EntityIds.accessRoute,
    metric: 'logistics.estimatedTravelTime',
    value: 18,
    unit: 'min',
    observedAt: SCENARIO_01_START_TIME - 2,
    receivedAt: SCENARIO_01_START_TIME,
    source: {
      type: 'external',
      id: 'road-authority-feed',
      organisation: 'Nowy Brzeg Road Authority',
    },
    quality: 'good',
    confidence: recentHumanReportConfidence,
    classification: 'report',
  },
];
